### ISSUE TITLE
how to use in ViewHolder

### ISSUE THREAD

**Issue by qiushui95** [satoshun/CoroutineAutoDispose#8]
can you give me a sample?Thanks

**Comment by qiushui95** [comment]
or how to use in ViewModel

**Comment by satoshun** [comment]
ok, I didn't consider using with ViewHolder. but I think about it within a few days.

**Comment by satoshun** [comment]
Hello, sorry late too response.
I published view(RecyclerView) support at 0.2.0 and added readme document.

**Comment by qiushui95** [comment]
@satoshun Thanks
